In [17]:
import os
import joblib
import pandas as pd

print(os.getcwd())

e:\customer-churn-predictor\notebooks

In [18]:
df = pd.read_csv("../data/churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [19]:
model = joblib.load("../models/churn_model.pkl")

In [20]:
X = df.drop("Churn", axis=1)
y = df["Churn"].map({"Yes": 1, "No": 0})

In [21]:
y_pred = model.predict(X)
y_proba = model.predict_proba(X)[:, 1]

In [22]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y, y_pred)
print(cm)

[[4997  177]
 [ 473 1396]]

In [23]:
tn, fp, fn, tp = cm.ravel()

print("False Negatives:", fn)

False Negatives: 473

In [24]:
df["pred"] = y_pred

missed = df[(df["Churn"] == "Yes") & (df["pred"] == 0)]
missed.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,pred
18,4190-MFLUW,Female,0,Yes,Yes,10,Yes,No,DSL,No,...,Yes,No,No,Month-to-month,No,Credit card (automatic),55.20,528.35,Yes,0
51,9420-LOJKX,Female,0,No,No,15,Yes,No,Fiber optic,Yes,...,No,Yes,Yes,Month-to-month,Yes,Credit card (automatic),99.10,1426.4,Yes,0
97,0278-YXOOG,Male,0,No,No,5,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,21.05,113.85,Yes,0
104,3192-NQECA,Male,0,Yes,No,68,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),110.00,7611.85,Yes,0
110,0486-HECZI,Male,0,Yes,No,55,Yes,Yes,Fiber optic,Yes,...,No,Yes,No,Month-to-month,Yes,Electronic check,96.75,5238.9,Yes,0

Model tends to miss high-risk long-tenure customers.